name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: |
          npx cypress run --spec "cypress/integration/retrieve_all_contacts_spec.js"
          npx cypress run --spec "cypress/integration/retrieve_specific_contact_spec.js"
          npx cypress run --spec "cypress/integration/non_existent_contact_spec.js"
          npx cypress run --spec "cypress/integration/create_contact_spec.js"
          npx cypress run --spec "cypress/integration/create_contact_missing_fields_spec.js"
          npx cypress run --spec "cypress/integration/update_contact_spec.js"
          npx cypress run --spec "cypress/integration/update_non_existent_contact_spec.js"
          npx cypress run --spec "cypress/integration/delete_contact_spec.js"
          npx cypress run --spec "cypress/integration/delete_non_existent_contact_spec.js"
          npx cypress run --spec "cypress/integration/search_contacts_first_name_spec.js"
          npx cypress run --spec "cypress/integration/search_contacts_email_spec.js"
          npx cypress run --spec "cypress/integration/invalid_search_parameters_spec.js"
