name: CI

on: [push, pull_request]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: npm install
        
      - name: Start server
        run: npm start &
        
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000
        
      - name: Run Cypress tests
        run: npx cypress run
        
  security-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'https://thinking-tester-contact-list.herokuapp.com/'