name: Test Workflow

on:
  push:
    branches:
      - YAML-TEST

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        browser: [chrome, firefox] # Add any other browsers you want to test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Install dependencies and set up environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      # Run unit tests
      - name: Run unit tests
        run: npm test

      # Configure parallel execution for UI tests
      - name: Run UI tests on ${{ matrix.browser }}
        run: |
          if [ "${{ matrix.browser }}" = "chrome" ]; then
            # Run Chrome UI tests
            npm run test:chrome
          elif [ "${{ matrix.browser }}" = "firefox" ]; then
            # Run Firefox UI tests
            npm run test:firefox
          fi