name: OWASP ZAP Baseline Scan

on:
  push:
    branches:
      - add-zap-baseline-scan
  pull_request:
    branches:
      - BASE-LINE

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.6.0
        with:
          target: 'https://juice-shop.herokuapp.com/#'
          rules_file: '.github/zap/rules.tsv'
          cmd_options: '-a -r zap_report.html'
