name: OWASP ZAP Baseline Scan

on:
  push:
    branches:
      - add-zap-baseline-scan
  pull_request:
    branches:
      - main

jobs:
  zap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://juice-shop.herokuapp.com'
          cmd_options: '-t https://juice-shop.herokuapp.com -r zap_report.html'

