name: Security Scan

on: [push, pull_request]

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.4.0
        with:
          target: 'https://thinking-tester-contact-list.herokuapp.com'
          rules_file_name: '.github/zap/rules.txt'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
